## Imaad Ullah
### Email: imaad3358@gmail.com

### Numpy Tutorials

In [1]:
import numpy as np

In [36]:
# Numpy array
a = np.array([2,5,1,])
a

array([2, 5, 1])

In [7]:
# Numpy 2D array
b = np.array([[2,2,2,2],[4,5,1,2]])
b

array([[2, 2, 2, 2],
       [4, 5, 1, 2]])

In [15]:
# to check the type 
print('Type of array "a" :\n',type(a))
print('\n\nType of array "b" :\n',type(b))

Type of array "a" :
 <class 'numpy.ndarray'>


Type of array "b" :
 <class 'numpy.ndarray'>


In [18]:
# Array from Random numbers
s = np.random.randint(12, size = (4,3))
s

array([[ 0,  7,  5],
       [11,  6,  0],
       [ 7, 10, 11],
       [ 5,  9,  6]])

In [22]:
# Dimension of array s
# Rows and columns
s.ndim

2

In [60]:
# 3D Array
d = np.random.randint(10, size=(3, 4, 5))
d

array([[[0, 6, 5, 8, 0],
        [1, 5, 6, 8, 2],
        [5, 5, 1, 0, 9],
        [9, 7, 1, 8, 0]],

       [[2, 5, 5, 1, 7],
        [3, 0, 4, 7, 3],
        [2, 4, 0, 1, 8],
        [3, 3, 7, 5, 9]],

       [[2, 4, 1, 7, 8],
        [2, 3, 3, 6, 4],
        [5, 8, 2, 3, 4],
        [6, 3, 8, 3, 7]]])

In [30]:
# 4D array
f = np.random.randint(23, size=(4, 5, 7))
f

array([[[ 1,  9, 19,  8,  2, 10, 19],
        [ 6,  1, 17,  4,  6,  1, 19],
        [ 0, 19, 14,  3,  7,  8, 16],
        [ 1, 21, 20, 17, 17,  2, 17],
        [ 1,  6,  7, 18,  5, 22, 16]],

       [[15, 15, 17,  1,  8,  6, 21],
        [13, 11,  7, 13, 22,  2, 18],
        [21,  8,  8,  9,  5,  3, 21],
        [21,  2,  4,  7, 16,  6,  4],
        [ 6, 12, 21,  8, 18, 12, 17]],

       [[11, 19, 18,  0, 17, 12,  0],
        [14,  2,  3, 17, 11, 12, 18],
        [ 4, 21,  4, 19, 16,  7,  4],
        [13, 12,  9, 12, 21, 18, 19],
        [14, 22,  4, 18,  2, 14, 19]],

       [[ 2,  1,  9, 14,  2,  0, 12],
        [ 4,  6,  3,  1, 14, 18,  6],
        [ 3, 19,  2,  5, 11,  5,  2],
        [17, 18,  9, 16,  3, 10,  7],
        [ 7, 15,  8,  9,  0, 13,  1]]])

In [32]:
# Size = number of rows * number of columns
# (4, 5, 7)  4 * 5 * 7 = 140
f.size

140

In [34]:
# Size = number of rows * number of columns
# 4 * 3 = 12
s.size

12

### Array Indexing: Accessing Single Elements

In [35]:
# first element of array a
a[0]

2

In [37]:
# second element of array a
a[1]

5

In [38]:
# last element of array a
a[-1]

1

In [39]:
s

array([[ 0,  7,  5],
       [11,  6,  0],
       [ 7, 10, 11],
       [ 5,  9,  6]])

In [41]:
# Second row third column element of s
s[1,2]

0

In [42]:
# Third row first column element of s
s[2,0]

7

In [43]:
# Last row last column element of s
s[-1,-1]

6

### we can also modify values of an array

In [44]:
# Modifying Last row last column element of s
s[-1,-1] = 45
s

array([[ 0,  7,  5],
       [11,  6,  0],
       [ 7, 10, 11],
       [ 5,  9, 45]])

In [45]:
# In arrays we can't have multiple types (int, float, str), in list we can but not in arrays
a[1] = 3.333
a

array([2, 3, 1])

### Array Slicing: Accessing Subarrays
``` python
x[start:stop:step]
```
By default it is
``start=0``, ``stop=``*``size of dimension``*, ``step=1``

In [47]:
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# First five elements (O:4)
z[:5]

array([0, 1, 2, 3, 4])

In [50]:
# from 4th element to the last element (4:9)
z[4:]

array([4, 5, 6, 7, 8, 9])

In [51]:
# start from 2 and end at 6 (2:6)
z[2:7]

array([2, 3, 4, 5, 6])

In [52]:
# start from 0 go to the end and skip every other element
z[::2]

array([0, 2, 4, 6, 8])

In [53]:
#start from 1 go to the end and skip every other element
z[1::2]

array([1, 3, 5, 7, 9])

In [54]:
# reversing an array
z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Multi-dimensional subarrays

In [55]:
s

array([[ 0,  7,  5],
       [11,  6,  0],
       [ 7, 10, 11],
       [ 5,  9, 45]])

In [58]:
# First two rows and first two columns
s[:2, :2]

array([[ 0,  7],
       [11,  6]])

In [63]:
aa = np.random.randint(20, size=(4, 5))
aa

array([[ 2, 19, 19,  7,  3],
       [ 6,  3, 11, 14, 16],
       [10, 18,  9,  6, 10],
       [19, 18,  7,  7,  6]])

In [68]:
# last two rows and first three columns
aa[2: , :3]

array([[10, 18,  9],
       [19, 18,  7]])

In [70]:
# third row and last four columns
aa[3, 1:]

array([18,  7,  7,  6])

In [77]:
# first column
aa[:, 0]

array([ 2,  6, 10, 19])

In [78]:
# first row
print('First Method: ', aa[0, :])
print('Second Method: ', aa[0])

First Method:  [ 2 19 19  7  3]
Second Method:  [ 2 19 19  7  3]


### Reshaping of Arrays

In [79]:
ar = np.arange(1, 10).reshape((3,3))
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
ss = np.random.random(12).reshape((3, 4))
ss

array([[0.56523341, 0.4814271 , 0.92784301, 0.60679301],
       [0.8731501 , 0.75559341, 0.21629041, 0.91686202],
       [0.55884655, 0.46529974, 0.61392743, 0.90804536]])

In [87]:
dd = np.linspace(1, 5).reshape((5, 10))
dd

array([[1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
        1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388],
       [1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
        2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041],
       [2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
        3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694],
       [3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
        3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347],
       [4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
        4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]])

In [94]:
x = np.arange(10,30)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [96]:
x.reshape(4, 5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Concatenation of arrays

In [98]:
x = np.array([2, 3, 4, 5])
y = np.array([1, 3, 8, 7])
conc = np.concatenate([x, y])
conc

array([2, 3, 4, 5, 1, 3, 8, 7])

In [100]:
z = np.array([99, 99, 100, 100])
np.concatenate([x, y, z])

array([  2,   3,   4,   5,   1,   3,   8,   7,  99,  99, 100, 100])

### Concatinating two dimensional array

In [106]:
a = np.random.randint(12, size=(4,3))
b = np.random.randint(10,22, size=(4,3))
a

array([[ 4,  5,  3],
       [10,  9,  3],
       [ 8,  7,  7],
       [ 9,  1, 11]])

In [107]:
b

array([[17, 20, 17],
       [10, 14, 14],
       [12, 20, 19],
       [19, 18, 14]])

In [108]:
np.concatenate([a, b])

array([[ 4,  5,  3],
       [10,  9,  3],
       [ 8,  7,  7],
       [ 9,  1, 11],
       [17, 20, 17],
       [10, 14, 14],
       [12, 20, 19],
       [19, 18, 14]])

In [112]:
np.concatenate([a, b], axis=1)

array([[ 4,  5,  3, 17, 20, 17],
       [10,  9,  3, 10, 14, 14],
       [ 8,  7,  7, 12, 20, 19],
       [ 9,  1, 11, 19, 18, 14]])

In [113]:
np.concatenate([a, b], axis=0)

array([[ 4,  5,  3],
       [10,  9,  3],
       [ 8,  7,  7],
       [ 9,  1, 11],
       [17, 20, 17],
       [10, 14, 14],
       [12, 20, 19],
       [19, 18, 14]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [114]:
q = np.array([1, 2, 3])
w = np.array([[3, 4, 5], [9, 8, 7]])
# vertically stack array
np.vstack([q, w])

array([[1, 2, 3],
       [3, 4, 5],
       [9, 8, 7]])

In [118]:
# Horizontally stack array
y = np.array([[99], [99]])

np.hstack([w, y])

array([[ 3,  4,  5, 99],
       [ 9,  8,  7, 99]])